#!/bin/sh

DEFAULT_INTERVAL=$((60 * 15)) # In seconds

while true; do
	find "$HOME/Pictures/Wallpapers" -type f \
	| while read -r img; do
		echo "$(</dev/urandom tr -dc a-zA-Z0-9 | head -c 8):$img"
	done \
	| sort -n | cut -d':' -f2- \
	| while read -r img; do
		echo "setting wallpaper: $img"
		hyprpaper unload all
		hyprpaper preload "$img"
		hyprpaper wallpaper ,"$img"
		sleep "${2:-$DEFAULT_INTERVAL}"
	done
done
