{ pkgs, variables, ... }:
let
  # Define your Catppuccin Mocha colors directly in Nix
  catppuccinMocha = {
    rosewater = "f5e0dc";
    flamingo = "f2cdcd";
    pink = "f5c2e7";
    mauve = "cba6f7";
    red = "f38ba8";
    maroon = "eba0ac";
    peach = "fab387";
    yellow = "f9e2af";
    green = "a6e3a1";
    teal = "94e2d5";
    sky = "89dceb";
    sapphire = "74c7ec";
    blue = "89b4fa";
    lavender = "b4befe";
    text = "cdd6f4";
    subtext1 = "bac2de";
    subtext0 = "a6adc8";
    overlay2 = "9399b2";
    overlay1 = "7f849c";
    overlay0 = "6c7086";
    surface2 = "585b70";
    surface1 = "45475a";
    surface0 = "313244";
    base = "1e1e2e";
    mantle = "181825";
    crust = "11111b";
  };
in
{
  # Generate the hyprlock.conf file
  xdg.configFile."hypr/hyprlock.conf".source = pkgs.writeText "hyprlock-config" ''
    # This file is generated by NixOS. Do not edit directly!
    # Based on your original ~/.config/hypr/hyprlock.conf

    # Define accent color using Catppuccin Mocha lavender
    # Hyprlock doesn't support variables like $accent, so we hardcode it
    # to the desired Catppuccin color.
    # $accent = $lavender (changed from mauve)
    # $accentAlpha = $lavenderAlpha (changed from mauve)
    # The font variable can remain as it's not a color
    $font = JetBrainsMono Nerd Font

    # GENERAL
    general {
        # disable_loading_bar = true
        hide_cursor = true
    }

    # BACKGROUND
    background {
        monitor =
        path = ${variables.wallpaper}
        blur_passes = 2
        color = 0x${catppuccinMocha.base} # Replaced $base with hex code
    }

    # TIME
    label {
        monitor =
        text = cmd[update:30000] echo "$(date +"%R")"
        color = 0x${catppuccinMocha.text} # Replaced $text with hex code
        font_size = 90
        font_family = $font
        position = -30, 0
        halign = right
        valign = top
    }

    # DATE
    label {
        monitor =
        text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
        color = 0x${catppuccinMocha.text} # Replaced $text with hex code
        font_size = 25
        font_family = $font
        position = -30, -150
        halign = right
        valign = top
    }

    # USER AVATAR

    image {
        monitor =
        #path = ~/.face
        size = 100
        border_color = 0x${catppuccinMocha.lavender} # Replaced $accent (now using lavender instead of mauve) with hex code

        position = 0, 75
        halign = center
        valign = center
    }

    # INPUT FIELD
    input-field {
        monitor =
        size = 300, 60
        outline_thickness = 4
        dots_size = 0.2
        dots_spacing = 0.2
        dots_center = true
        outer_color = 0x${catppuccinMocha.lavender} # Replaced $accent (now using lavender instead of mauve) with hex code
        inner_color = 0x${catppuccinMocha.surface0} # Replaced $surface0 with hex code
        font_color = 0x${catppuccinMocha.text} # Replaced $text with hex code
        fade_on_empty = false
        # For Pango markup, ensure the hex code is directly inside the quotes.
        # Catppuccin Alpha colors are just the 6-digit hex, so we use them directly.
        # If Hyprlock's Pango parser still errors, try changing 0x to # here.
        placeholder_text = <span foreground="0x${catppuccinMocha.text}"><i >󰌾 Logged in as </i><span foreground="0x${catppuccinMocha.lavender}">$USER</span></span>
        hide_input = false
        check_color = 0x${catppuccinMocha.lavender} # Replaced $accent (now using lavender instead of mauve) with hex code
        fail_color = 0x${catppuccinMocha.red} # Replaced $red with hex code
        fail_text = <i >$FAIL <b>($ATTEMPTS)</b></i>
        capslock_color = 0x${catppuccinMocha.yellow} # Replaced $yellow with hex code
        position = 0, -35
        halign = center
        valign = center
    }
  '';
}
