# SOPS configuration
creation_rules:
  # Host-level secrets (NixOS system configuration)
  - path_regex: hosts/.*
    age: age1zln4nlxttpqehayq4wmve2fcvl80zs2mt0xyh5c7ur56hvztdvdqsnv362
  
  # User-level secrets (Home Manager)
  - path_regex: users/.*
    age: age1zln4nlxttpqehayq4wmve2fcvl80zs2mt0xyh5c7ur56hvztdvdqsnv362
